services:
  chyrp-lite:
    image: gutenye/chyrp-lite
    build:
      platforms:
        - linux/arm64   
        - linux/amd64
    container_name: chyrp-lite
    restart: unless-stopped
    volumes:
      - data:/data
      - uploads:/var/www/html/uploads
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - mysql

# Use SQLite if don't know which database to choose. Set the database path to
# "/data/db.sqlite" during install. If you need PostgreSQL or MySQL,
# uncomment the one you want and set "Host" to "postgres" or "mysql"
# accordingly during install.

#  postgres:
#    image: postgres
#    restart: unless-stopped
#    volumes:
#      - db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: chyrp-lite
#      POSTGRES_USER: chyrp-lite
#      POSTGRES_PASSWORD: <password>

  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  data:
  uploads:
  db:
